## Copyright 2022 Google LLC
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     https://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.

FROM alpine:3.20

USER root

RUN apk update && apk add --no-cache tar curl gzip nginx php83 php83-fpm php83-opcache \
  php83-mysqli php83-iconv php83-mbstring php83-curl php83-openssl php83-tokenizer php83-intl \
  php83-soap php83-xmlreader php83-fileinfo php83-sodium php83-exif php83-ctype php83-zip \
  php83-xmlwriter php83-gd php83-simplexml php83-dom php83-xml php83-redis php83-pecl-igbinary \
  php83-phar php83-posix php83-pecl-zstd envsubst tzdata sudo vim icu-data-full \
  && ln -s /usr/bin/php83 /usr/bin/php

# install correct composer for php83
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
  php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
  php composer-setup.php && \
  php -r "unlink('composer-setup.php');" && \
  mv composer.phar /usr/local/bin/composer;

# Optional packages
RUN apk add --no-cache aspell graphviz ghostscript python3 poppler-utils clamav

RUN adduser -D -g 'www' www

ARG MOODLE_ROOT_PATH='/moodleroot-instance1' \
    MOODLE_DATAROOT_PATH='/moodleroot-instance1/moodledata' \
    MOODLE_PATH='/moodleroot-instance1/moodle'

ENV MOODLE_URL='' \
    MOOSH_URL='' \
    LANG='' \
    LANGUAGE='' \
    MOODLE_LANGUAGE='' \
    SITE_URL='' \
    MOODLE_ROOT_PATH=$MOODLE_ROOT_PATH \
    MOODLE_DATAROOT_PATH=$MOODLE_DATAROOT_PATH \
    MOODLE_PATH=$MOODLE_PATH \
    DB_TYPE='' \
    DB_HOST='' \
    DB_HOST_PORT='' \
    DB_NAME='' \
    DB_USER='' \
    DB_PASS='' \
    DB_PREFIX='' \
    MOODLE_SITENAME='' \
    MOODLE_SITESUMMARY='' \
    MOODLE_USERNAME='' \
    MOODLE_PASSWORD='' \
    MOODLE_EMAIL='' \
    DB_READ_REPLICA_HOST='' \
    DB_READ_REPLICA_PORT='' \
    DB_READ_REPLICA_USER='' \
    DB_READ_REPLICA_PASSWORD='' \
    REDIS_SESSION_ID_HOST="" \
    REDIS_SESSION_ID_PORT= \
    REDIS_SESSION_ID_AUTH_STRING="" \
    REDIS_APP_IP_AND_PORT="" \
    REDIS_APP_AUTH_STRING="" \
    REDIS_SESSION_IP_AND_PORT="" \
    REDIS_SESSION_AUTH_STRING="" \
    REDIS_LOCK_HOST_AND_PORT=""\
    REDIS_LOCK_AUTH_STRING=""\
    SSLPROXY='' \
    NOEMAIL_EVER='' \
    SMTP_HOST='' \
    SMTP_PORT='' \
    SMTP_USER='' \
    SMTP_PASSWORD='' \
    SMTP_PROTOCOL='' \
    MOODLE_MAIL_NOREPLY_ADDRESS='' \
    MOODLE_MAIL_PREFIX=''

COPY ["./base/opt", "/opt"]

COPY --chown=root:root ["./base/etc", "/root/etc"]
COPY --chown=www:www ["./config.php.template", "/root/.templates/"]
COPY --chown=www:www ["./base/moodle", "/root/.templates/moodle"]

RUN chown -R www:www /var/lib/nginx \
    && chmod 1700 /opt/*.sh \
    && chown -R www:www /opt/*.sh \
    && echo "America/Sao_Paulo" >  /etc/timezone

ENTRYPOINT [ "/opt/entrypoint.sh" ]
